# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-01 01:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('widget_def', '0054_auto_20160503_1627'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parametisation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=128, unique=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='ParametisationKey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=120)),
                ('param', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='widget_def.Parametisation')),
            ],
            options={
                'ordering': ('param', 'key'),
            },
        ),
        migrations.AlterField(
            model_name='statistic',
            name='unit_prefix',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='statistic',
            name='unit_suffix',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='statistic',
            name='unit_underfix',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='widgetdefinition',
            name='parametisation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='widget_def.Parametisation'),
        ),
        migrations.AlterUniqueTogether(
            name='parametisationkey',
            unique_together=set([('param', 'key')]),
        ),
    ]
