# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-02 03:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('widget_def', '0055_auto_20160601_1145'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParameterValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=120)),
                ('property_type', models.SmallIntegerField(choices=[(0, b'integer'), (1, b'string'), (2, b'boolean'), (3, b'decimal')])),
                ('strval', models.CharField(blank=True, max_length=255, null=True)),
                ('intval', models.IntegerField(blank=True, null=True)),
                ('boolval', models.NullBooleanField()),
                ('decval', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
            ],
            options={
                'ordering': ('pv', 'key'),
            },
        ),
        migrations.CreateModel(
            name='ParametisationValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('param', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='widget_def.Parametisation')),
                ('views', models.ManyToManyField(to='widget_def.WidgetView')),
            ],
        ),
        migrations.AddField(
            model_name='parametervalue',
            name='pv',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='widget_def.ParametisationValue'),
        ),
        migrations.AlterUniqueTogether(
            name='parametervalue',
            unique_together=set([('pv', 'key')]),
        ),
    ]
