# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-06 01:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('widget_def', '0056_auto_20160602_1323'),
    ]

    operations = [
        migrations.AddField(
            model_name='geowindow',
            name='view_override',
            field=models.BooleanField(default=False),
        ),
    ]
