# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-30 23:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('widget_def', '0058_auto_20160617_1124'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='geodatasetdeclaration',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='geodatasetdeclaration',
            name='dataset',
        ),
        migrations.RemoveField(
            model_name='geodatasetdeclaration',
            name='frequency',
        ),
        migrations.RemoveField(
            model_name='geodatasetdeclaration',
            name='location',
        ),
        migrations.RemoveField(
            model_name='geodatasetdeclaration',
            name='theme',
        ),
        migrations.RemoveField(
            model_name='location',
            name='geo_window',
        ),
        migrations.AlterUniqueTogether(
            name='widgetdeclaration',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='widgetdeclaration',
            name='definition',
        ),
        migrations.RemoveField(
            model_name='widgetdeclaration',
            name='frequency',
        ),
        migrations.RemoveField(
            model_name='widgetdeclaration',
            name='location',
        ),
        migrations.RemoveField(
            model_name='widgetdeclaration',
            name='theme',
        ),
        migrations.AddField(
            model_name='graphdefinition',
            name='cluster_label',
            field=models.CharField(default=b'cluster', help_text=b'Not used for line graphs', max_length=120),
        ),
        migrations.AddField(
            model_name='graphdefinition',
            name='dataset_label',
            field=models.CharField(default=b'dataset', max_length=120),
        ),
        migrations.DeleteModel(
            name='Frequency',
        ),
        migrations.DeleteModel(
            name='GeoDatasetDeclaration',
        ),
        migrations.DeleteModel(
            name='Location',
        ),
        migrations.DeleteModel(
            name='Theme',
        ),
        migrations.DeleteModel(
            name='WidgetDeclaration',
        ),
    ]
