# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-06 23:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('widget_def', '0059_auto_20160701_0929'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='statistic',
            unique_together=set([('tile', 'url')]),
        ),
    ]
