# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-06 23:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('widget_def', '0060_auto_20160707_0937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='widgetfamily',
            name='name',
            field=models.CharField(max_length=80),
        ),
    ]
