# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-20 03:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('widget_def', '0061_auto_20160707_0950'),
    ]

    operations = [
        migrations.AddField(
            model_name='widgetview',
            name='external_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
