# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-21 04:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('widget_def', '0062_widgetview_external_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='graphdataset',
            name='use_error_bars',
            field=models.BooleanField(default=False),
        ),
    ]
