# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-02 05:30
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('widget_def', '0063_graphdataset_use_error_bars'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statistic',
            name='stat_type',
            field=models.SmallIntegerField(choices=[(1, b'string'), (8, b'long_string'), (2, b'numeric'), (3, b'string_kv_list'), (4, b'numeric_kv_list'), (5, b'string_list'), (9, b'long_string_list'), (6, b'am_pm'), (7, b'event_list'), (10, b'hierarchical_event_list'), (11, b'null')]),
        ),
        migrations.AlterField(
            model_name='tiledefinition',
            name='list_label_width',
            field=models.SmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
