# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-09 06:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('widget_def', '0065_auto_20160804_1526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viewproperty',
            name='strval',
            field=models.TextField(blank=True, null=True),
        ),
    ]
