# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-24 04:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('widget_def', '0067_auto_20160823_1058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='sort_order',
            field=models.IntegerField(unique=True),
        ),
    ]
