# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-31 02:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('widget_def', '0068_auto_20160824_1423'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='graphcluster',
            name='dynamic_label',
        ),
        migrations.AddField(
            model_name='graphdefinition',
            name='dynamic_clusters',
            field=models.BooleanField(default=False),
        ),
    ]
