# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-13 04:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('widget_def', '0072_auto_20160913_1113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rawdatasetcolumn',
            name='description',
            field=models.TextField(blank=True, help_text=b'A detailed description of the column', null=True),
        ),
        migrations.AlterField(
            model_name='rawdatasetcolumn',
            name='heading',
            field=models.CharField(help_text=b'The column heading, as used in a csv file', max_length=128),
        ),
        migrations.AlterField(
            model_name='rawdatasetcolumn',
            name='rds',
            field=models.ForeignKey(help_text=b'The raw dataset', on_delete=django.db.models.deletion.CASCADE, to='widget_def.RawDataSet'),
        ),
        migrations.AlterField(
            model_name='rawdatasetcolumn',
            name='sort_order',
            field=models.IntegerField(help_text=b'Determines the column order within a raw dataset'),
        ),
        migrations.AlterField(
            model_name='rawdatasetcolumn',
            name='url',
            field=models.SlugField(help_text=b'A short symbolic name for the column, used by default in a json file'),
        ),
    ]
