# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-27 00:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('widget_def', '0076_auto_20161005_1112'),
    ]

    operations = [
        migrations.CreateModel(
            name='ViewFamily',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text=b'The display name for the secondary menu', max_length=120, null=True)),
                ('label', models.SlugField(help_text=b'The symbolic label for the view, as used in the API.', unique=True)),
                ('sort_order', models.IntegerField(help_text=b'The secondary menus for a view are sorted by this field', unique=True)),
            ],
            options={
                'ordering': ('sort_order',),
            },
        ),
        migrations.CreateModel(
            name='ViewFamilyMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text=b'How this view is labeled in the family menu.', max_length=120)),
                ('sort_order', models.IntegerField(help_text=b'How the views are sorted within the family', unique=True)),
                ('family', models.ForeignKey(help_text=b'The family belonged to', on_delete=django.db.models.deletion.CASCADE, to='widget_def.ViewFamily')),
                ('view', models.ForeignKey(help_text=b'The view belonging to', on_delete=django.db.models.deletion.CASCADE, to='widget_def.WidgetView')),
            ],
            options={
                'ordering': ('family', 'sort_order'),
            },
        ),
        migrations.AlterUniqueTogether(
            name='viewfamilymember',
            unique_together=set([('family', 'sort_order'), ('family', 'view'), ('family', 'name')]),
        ),
    ]
