# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-14 03:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('widget_def', '0078_auto_20161027_1135'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rawdataset',
            options={'ordering': ('widget', 'url')},
        ),
    ]
