# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-01-09 00:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('widget_def', '0079_auto_20161114_1430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='graphdataset',
            name='colour',
            field=models.CharField(help_text=b'The colour of the dataset. Interpretation is implementation-specific. Typically a word colour hint rather than an explicit rgb value. (May be parametised)', max_length=50),
        ),
        migrations.AlterField(
            model_name='graphdataset',
            name='hyperlink',
            field=models.URLField(blank=True, help_text=b'An optional external URL for this dataset to link to. (May be parametised)', null=True),
        ),
        migrations.AlterField(
            model_name='graphdataset',
            name='label',
            field=models.CharField(help_text=b'A longer human-readable description of the dataset. (May be parametised)', max_length=80, verbose_name=b'name'),
        ),
    ]
