# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-02-01 03:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('widget_def', '0080_auto_20170109_1102'),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(help_text=b'The key (lookup value) of this property', max_length=255)),
                ('value', models.CharField(help_text=b'The value (mapped value) of this property', max_length=1024)),
            ],
            options={
                'ordering': ['group', 'key'],
            },
        ),
        migrations.CreateModel(
            name='PropertyGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text=b'Descriptive name of the Property Group', max_length=80, unique=True)),
                ('label', models.SlugField(help_text=b'Short symbolic name of the Property Group, as used in API', unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='property',
            name='group',
            field=models.ForeignKey(help_text=b'The group this property belongs to', on_delete=django.db.models.deletion.CASCADE, to='widget_def.PropertyGroup'),
        ),
        migrations.AlterUniqueTogether(
            name='property',
            unique_together=set([('group', 'key')]),
        ),
    ]
