# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-02-16 23:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('widget_def', '0082_auto_20170202_0958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='graphdefinition',
            name='heading',
            field=models.CharField(blank=True, help_text=b'The heading for the graph, as displayed to the end-user.', max_length=180, null=True),
        ),
    ]
