# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-02-22 03:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('widget_def', '0083_auto_20170217_1055'),
    ]

    operations = [
        migrations.AddField(
            model_name='graphdefinition',
            name='vertical_axis_buffer',
            field=models.DecimalField(decimal_places=0, default='0.0', max_digits=3),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='graphcluster',
            name='graph',
            field=models.ForeignKey(help_text=b'The graph the cluster belongs to', on_delete=django.db.models.deletion.CASCADE, to='widget_def.GraphDefinition'),
        ),
        migrations.AlterField(
            model_name='graphcluster',
            name='hyperlink',
            field=models.URLField(blank=True, help_text=b'An optional external URL to link for this cluster ', null=True),
        ),
        migrations.AlterField(
            model_name='graphcluster',
            name='label',
            field=models.CharField(help_text=b'A longer descriptive name for the cluster, suitable for presentation to an end user.', max_length=80, verbose_name=b'name'),
        ),
        migrations.AlterField(
            model_name='graphcluster',
            name='sort_order',
            field=models.IntegerField(help_text=b'How to sort the cluster within the graph'),
        ),
        migrations.AlterField(
            model_name='graphcluster',
            name='url',
            field=models.SlugField(help_text=b'A short symbolic label for the cluster, as used in the API', verbose_name=b'label'),
        ),
    ]
