# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-02-27 01:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('widget_def', '0084_auto_20170222_1412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='widgetfamily',
            name='name',
            field=models.CharField(help_text=b'The name (main heading) of widgets in this family. May be parametised.', max_length=120),
        ),
    ]
