# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-02-28 23:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('widget_def', '0085_auto_20170227_1246'),
    ]

    operations = [
        migrations.AddField(
            model_name='graphdataset',
            name='hide_from_legend',
            field=models.BooleanField(default=False, help_text=b'If true, this dataset will be suppressed from the legend.'),
        ),
    ]
