# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-03-01 00:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('widget_def', '0087_auto_20170301_1037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='graphdefinition',
            name='vertical_axis_buffer',
            field=models.DecimalField(decimal_places=0, default=b'0', max_digits=3),
        ),
    ]
