# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-07 01:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('widget_def', '0090_viewwidgetdeclaration_state_cache'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geocolourpoint',
            name='scale',
            field=models.ForeignKey(help_text=b'The colour scale', on_delete=django.db.models.deletion.CASCADE, related_name='points', to='widget_def.GeoColourScale'),
        ),
        migrations.AlterField(
            model_name='geopropertydefinition',
            name='dataset',
            field=models.ForeignKey(help_text=b'The GeoDataset the property is defined for', on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='widget_def.GeoDataset'),
        ),
        migrations.AlterField(
            model_name='graphdataset',
            name='graph',
            field=models.ForeignKey(help_text=b'The graph the dataset belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='datasets', to='widget_def.GraphDefinition'),
        ),
        migrations.AlterField(
            model_name='graphdefinition',
            name='tile',
            field=models.OneToOneField(help_text=b'The widget tile this graph is to be displayed in', on_delete=django.db.models.deletion.CASCADE, related_name='graph', to='widget_def.TileDefinition'),
        ),
        migrations.AlterField(
            model_name='graphdisplayoptions',
            name='graph',
            field=models.OneToOneField(help_text=b'The graph', on_delete=django.db.models.deletion.CASCADE, related_name='options', to='widget_def.GraphDefinition'),
        ),
        migrations.AlterField(
            model_name='gridcolumn',
            name='grid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='columns', to='widget_def.GridDefinition'),
        ),
        migrations.AlterField(
            model_name='griddefinition',
            name='tile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='grid', to='widget_def.TileDefinition'),
        ),
        migrations.AlterField(
            model_name='gridrow',
            name='grid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='widget_def.GridDefinition'),
        ),
        migrations.AlterField(
            model_name='iconcode',
            name='scale',
            field=models.ForeignKey(help_text=b'The IconLibrary this IconCode belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='codes', to='widget_def.IconLibrary', verbose_name=b'Library'),
        ),
        migrations.AlterField(
            model_name='parametisationkey',
            name='param',
            field=models.ForeignKey(help_text=b'The Parametisation', on_delete=django.db.models.deletion.CASCADE, related_name='pkeys', to='widget_def.Parametisation'),
        ),
        migrations.AlterField(
            model_name='pointcolourrange',
            name='colour_map',
            field=models.ForeignKey(help_text=b'The PointColourMap object', on_delete=django.db.models.deletion.CASCADE, related_name='ranges', to='widget_def.PointColourMap'),
        ),
        migrations.AlterField(
            model_name='property',
            name='group',
            field=models.ForeignKey(help_text=b'The group this property belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='widget_def.PropertyGroup'),
        ),
        migrations.AlterField(
            model_name='rawdataset',
            name='widget',
            field=models.ForeignKey(help_text=b'The Widget this dataset belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='raw_datasets', to='widget_def.WidgetDefinition'),
        ),
        migrations.AlterField(
            model_name='rawdatasetcolumn',
            name='rds',
            field=models.ForeignKey(help_text=b'The raw dataset', on_delete=django.db.models.deletion.CASCADE, related_name='columns', to='widget_def.RawDataSet'),
        ),
        migrations.AlterField(
            model_name='statistic',
            name='tile',
            field=models.ForeignKey(help_text=b'The widget tile this statistic appears in', on_delete=django.db.models.deletion.CASCADE, related_name='statistics', to='widget_def.TileDefinition'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='category',
            field=models.ForeignKey(help_text=b'The parent category', on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='widget_def.Category'),
        ),
        migrations.AlterField(
            model_name='tiledefinition',
            name='widget',
            field=models.ForeignKey(help_text=b'The widget the tile is part of', on_delete=django.db.models.deletion.CASCADE, related_name='tiles', to='widget_def.WidgetDefinition'),
        ),
        migrations.AlterField(
            model_name='trafficlightautorule',
            name='strategy',
            field=models.ForeignKey(help_text=b'The automation strategy this rule is a part of', on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='widget_def.TrafficLightAutoStrategy'),
        ),
        migrations.AlterField(
            model_name='trafficlightscalecode',
            name='scale',
            field=models.ForeignKey(help_text=b'The traffic light scale', on_delete=django.db.models.deletion.CASCADE, related_name='codes', to='widget_def.TrafficLightScale'),
        ),
        migrations.AlterField(
            model_name='viewfamilymember',
            name='family',
            field=models.ForeignKey(help_text=b'The family belonged to', on_delete=django.db.models.deletion.CASCADE, related_name='members', to='widget_def.ViewFamily'),
        ),
        migrations.AlterField(
            model_name='viewfamilymember',
            name='view',
            field=models.ForeignKey(help_text=b'The view belonging to', on_delete=django.db.models.deletion.CASCADE, related_name='family_memberships', to='widget_def.WidgetView'),
        ),
        migrations.AlterField(
            model_name='viewgeodatasetdeclaration',
            name='dataset',
            field=models.ForeignKey(help_text=b'The GeoDataset to include in the WidgetView', on_delete=django.db.models.deletion.CASCADE, related_name='declarations', to='widget_def.GeoDataset'),
        ),
        migrations.AlterField(
            model_name='viewproperty',
            name='view',
            field=models.ForeignKey(help_text=b'The view this property belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='widget_def.WidgetView'),
        ),
        migrations.AlterField(
            model_name='viewwidgetdeclaration',
            name='definition',
            field=models.ForeignKey(help_text=b'The WidgetDefinition to include in the WidgetView', on_delete=django.db.models.deletion.CASCADE, related_name='views', to='widget_def.WidgetDefinition'),
        ),
        migrations.AlterField(
            model_name='widgetdefinition',
            name='family',
            field=models.ForeignKey(help_text=b'The widget family', on_delete=django.db.models.deletion.CASCADE, related_name='definitions', to='widget_def.WidgetFamily'),
        ),
        migrations.AlterField(
            model_name='widgetview',
            name='name',
            field=models.CharField(help_text=b'The display name for the view, as displayed in links to the view, and in the view itself', max_length=120, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='widgetview',
            unique_together=set([('parent', 'sort_order')]),
        ),
    ]
