# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-02-08 02:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure_npa_uploader', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InfrastructureKeyProjects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.SmallIntegerField(choices=[(1, 'NSW'), (2, 'Vic'), (3, 'Qld'), (4, 'WA'), (5, 'SA'), (6, 'Tas'), (7, 'ACT'), (8, 'NT'), (100, 'Australia')])),
                ('project', models.CharField(max_length=255)),
                ('milestones', models.TextField()),
                ('status', models.SmallIntegerField(choices=[(1, 'Completed'), (2, 'In progress'), (3, 'Not due to commence'), (4, 'Not completed and past agreed timeframe'), (5, 'Not applicable')])),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InfrastructureProjects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.SmallIntegerField(choices=[(1, 'NSW'), (2, 'Vic'), (3, 'Qld'), (4, 'WA'), (5, 'SA'), (6, 'Tas'), (7, 'ACT'), (8, 'NT'), (100, 'Australia')])),
                ('year', models.SmallIntegerField()),
                ('financial_year', models.BooleanField()),
                ('multi_year', models.IntegerField(default=1)),
                ('completed', models.DecimalField(decimal_places=0, max_digits=4)),
                ('underway', models.DecimalField(decimal_places=0, max_digits=4)),
                ('pending', models.DecimalField(decimal_places=0, max_digits=4)),
                ('completed_cost', models.DecimalField(decimal_places=0, max_digits=13)),
                ('underway_cost', models.DecimalField(decimal_places=0, max_digits=13)),
                ('pending_cost', models.DecimalField(decimal_places=0, max_digits=13)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='InfrastructureKeyProjectData',
        ),
        migrations.DeleteModel(
            name='InfrastructureProjectCounts',
        ),
        migrations.DeleteModel(
            name='InfrastructureProjectFundingProportion',
        ),
        migrations.AlterUniqueTogether(
            name='infrastructureprojects',
            unique_together=set([('state', 'year')]),
        ),
        migrations.AlterUniqueTogether(
            name='infrastructurekeyprojects',
            unique_together=set([('state', 'project')]),
        ),
    ]
