# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-02-10 00:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indigenous_child_mortality_uploader', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='indigenouschildmortalitynationaldata',
            options={'ordering': ('year', 'state')},
        ),
        migrations.AlterModelOptions(
            name='indigenouschildmortalitystatedata',
            options={'ordering': ('year', 'state')},
        ),
        migrations.AddField(
            model_name='indigenouschildmortalitynationaldata',
            name='indigenous_target',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='indigenouschildmortalitynationaldata',
            name='non_indigenous_projected',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='indigenouschildmortalitynationaldata',
            name='variability_lower',
            field=models.DecimalField(decimal_places=1, default=270.0, max_digits=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='indigenouschildmortalitynationaldata',
            name='variability_upper',
            field=models.DecimalField(decimal_places=1, default=190.0, max_digits=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='indigenouschildmortalitystatedata',
            name='indigenous_deaths',
            field=models.IntegerField(default=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='indigenouschildmortalitystatedata',
            name='non_indigenous_deaths',
            field=models.IntegerField(default=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='indigenouschildmortalitystatedata',
            name='rate_diff',
            field=models.DecimalField(decimal_places=1, default=1.5, max_digits=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='indigenouschildmortalitystatedata',
            name='rate_ratio',
            field=models.DecimalField(decimal_places=1, default=30.0, max_digits=5),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='indigenouschildmortalitynationaldata',
            name='indigenous',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='indigenouschildmortalitynationaldata',
            name='non_indigenous',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True),
        ),
    ]
