# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-02-01 01:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills_cert3_uploader', '0002_skillscert3data_multi_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='skillscert3data',
            name='rse',
            field=models.DecimalField(decimal_places=1, default=1.0, max_digits=3),
            preserve_default=False,
        ),
    ]
