# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-02-14 00:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IndigenousNaplanData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.SmallIntegerField(choices=[(1, 'NSW'), (2, 'Vic'), (3, 'Qld'), (4, 'WA'), (5, 'SA'), (6, 'Tas'), (7, 'ACT'), (8, 'NT'), (100, 'Australia')])),
                ('year_lvl', models.IntegerField()),
                ('subject', models.SmallIntegerField(choices=[(1, 'Reading'), (2, 'Numeracy')])),
                ('indig_proportion_above_nms', models.DecimalField(decimal_places=1, max_digits=5)),
                ('indig_confidence_interval', models.DecimalField(decimal_places=1, max_digits=5)),
                ('indig_trajectory', models.DecimalField(decimal_places=1, max_digits=5)),
            ],
            options={
                'ordering': ('state', 'subject', 'year_lvl'),
                'abstract': False,
            },
        ),
        migrations.AlterUniqueTogether(
            name='indigenousnaplandata',
            unique_together=set([('state', 'subject', 'year_lvl')]),
        ),
    ]
