# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-02-08 22:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legal_assistance_total_services_uploader', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LegalAssistData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.SmallIntegerField(choices=[(1, 'NSW'), (2, 'Vic'), (3, 'Qld'), (4, 'WA'), (5, 'SA'), (6, 'Tas'), (7, 'ACT'), (8, 'NT'), (100, 'Australia')])),
                ('start_date', models.DateField()),
                ('lac', models.DecimalField(decimal_places=1, max_digits=4)),
                ('clc', models.DecimalField(decimal_places=1, max_digits=4)),
                ('lac_benchmark', models.DecimalField(decimal_places=1, max_digits=4)),
                ('clc_benchmark', models.DecimalField(decimal_places=1, max_digits=4)),
            ],
            options={
                'ordering': ('state', 'start_date'),
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='LegalAssistTotalServices',
        ),
        migrations.AlterUniqueTogether(
            name='legalassistdata',
            unique_together=set([('state', 'start_date')]),
        ),
    ]
