# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-01 05:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education_ecenqs_uploader', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='educationecenqsdata',
            name='meeting_nqs',
            field=models.DecimalField(decimal_places=0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='educationecenqsdata',
            name='no_rating',
            field=models.DecimalField(decimal_places=0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='educationecenqsdata',
            name='working_towards',
            field=models.DecimalField(decimal_places=0, max_digits=6),
        ),
    ]
