# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-30 03:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EducationNaplanData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.SmallIntegerField(choices=[(1, 'NSW'), (2, 'Vic'), (3, 'Qld'), (4, 'WA'), (5, 'SA'), (6, 'Tas'), (7, 'ACT'), (8, 'NT'), (100, 'Australia')])),
                ('year', models.SmallIntegerField()),
                ('financial_year', models.BooleanField()),
                ('multi_year', models.IntegerField(default=1)),
                ('year3_lit_score', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('year5_lit_score', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('year7_lit_score', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('year9_lit_score', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('year3_lit_nms', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('year5_lit_nms', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('year7_lit_nms', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('year9_lit_nms', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('year3_num_score', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('year5_num_score', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('year7_num_score', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('year9_num_score', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('year3_num_nms', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('year5_num_nms', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('year7_num_nms', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('year9_num_nms', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterUniqueTogether(
            name='educationnaplandata',
            unique_together=set([('state', 'year')]),
        ),
    ]
