# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-01-31 23:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education_naplan_uploader', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='educationnaplandata',
            name='year3_lit_nms_rse',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='educationnaplandata',
            name='year3_lit_nms_uncertainty',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='educationnaplandata',
            name='year3_lit_score_rse',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='educationnaplandata',
            name='year3_lit_score_uncertainty',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='educationnaplandata',
            name='year3_num_nms_rse',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='educationnaplandata',
            name='year3_num_nms_uncertainty',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='educationnaplandata',
            name='year3_num_score_rse',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='educationnaplandata',
            name='year3_num_score_uncertainty',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='educationnaplandata',
            name='year5_lit_nms_rse',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='educationnaplandata',
            name='year5_lit_nms_uncertainty',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='educationnaplandata',
            name='year5_lit_score_rse',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='educationnaplandata',
            name='year5_lit_score_uncertainty',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='educationnaplandata',
            name='year5_num_nms_rse',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='educationnaplandata',
            name='year5_num_nms_uncertainty',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='educationnaplandata',
            name='year5_num_score_rse',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='educationnaplandata',
            name='year5_num_score_uncertainty',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='educationnaplandata',
            name='year7_lit_nms_rse',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='educationnaplandata',
            name='year7_lit_nms_uncertainty',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='educationnaplandata',
            name='year7_lit_score_rse',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='educationnaplandata',
            name='year7_lit_score_uncertainty',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='educationnaplandata',
            name='year7_num_nms_rse',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='educationnaplandata',
            name='year7_num_nms_uncertainty',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='educationnaplandata',
            name='year7_num_score_rse',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='educationnaplandata',
            name='year7_num_score_uncertainty',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='educationnaplandata',
            name='year9_lit_nms_rse',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='educationnaplandata',
            name='year9_lit_nms_uncertainty',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='educationnaplandata',
            name='year9_lit_score_rse',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='educationnaplandata',
            name='year9_lit_score_uncertainty',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='educationnaplandata',
            name='year9_num_nms_rse',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='educationnaplandata',
            name='year9_num_nms_uncertainty',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='educationnaplandata',
            name='year9_num_score_rse',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='educationnaplandata',
            name='year9_num_score_uncertainty',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True),
        ),
    ]
