# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-02-10 00:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('education_naplan_uploader', '0002_auto_20170201_1002'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='educationnaplandata',
            options={'ordering': ('year', 'state')},
        ),
    ]
