# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-02-15 21:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disability_labour_participation_uploader', '0003_auto_20170210_1127'),
    ]

    operations = [
        migrations.AddField(
            model_name='disabilitylabourparticipation',
            name='rse_female',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='disabilitylabourparticipation',
            name='rse_male',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True),
        ),
    ]
