# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-01-31 03:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education_yr12_uploader', '0002_educationyr12cert3attainmentdata_multi_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='educationyr12cert3attainmentdata',
            name='rse',
            field=models.DecimalField(decimal_places=1, default=1.0, max_digits=3),
            preserve_default=False,
        ),
    ]
