# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-02-10 00:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('education_yr12_uploader', '0003_educationyr12cert3attainmentdata_rse'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='educationyr12cert3attainmentdata',
            options={'ordering': ('year', 'state')},
        ),
    ]
