# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-02-16 00:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MentalHealthProjects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.SmallIntegerField(choices=[(1, 'NSW'), (2, 'Vic'), (3, 'Qld'), (4, 'WA'), (5, 'SA'), (6, 'Tas'), (7, 'ACT'), (8, 'NT'), (100, 'Australia')])),
                ('project', models.CharField(max_length=255)),
                ('progress', models.TextField()),
                ('status', models.SmallIntegerField(choices=[(1, 'Completed')])),
            ],
            options={
                'ordering': ('state', 'project'),
                'abstract': False,
            },
        ),
        migrations.AlterUniqueTogether(
            name='mentalhealthprojects',
            unique_together=set([('state', 'project')]),
        ),
    ]
