# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-02-13 00:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SkillsReformData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.SmallIntegerField(choices=[(1, 'NSW'), (2, 'Vic'), (3, 'Qld'), (4, 'WA'), (5, 'SA'), (6, 'Tas'), (7, 'ACT'), (8, 'NT'), (100, 'Australia')])),
                ('assessment', models.CharField(max_length=256)),
                ('assessment_sort_order', models.IntegerField()),
                ('performance_indicator', models.CharField(max_length=256)),
                ('performance_indicator_sort_order', models.IntegerField()),
                ('status', models.CharField(max_length=80)),
            ],
            options={
                'ordering': ['state', 'assessment_sort_order', 'performance_indicator_sort_order'],
                'abstract': False,
            },
        ),
        migrations.AlterUniqueTogether(
            name='skillsreformdata',
            unique_together=set([('state', 'assessment_sort_order', 'performance_indicator_sort_order'), ('state', 'assessment', 'performance_indicator')]),
        ),
    ]
