# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-02-13 01:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skills_reform_uploader', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='skillsreformdata',
            options={'ordering': ['assessment_sort_order', 'performance_indicator_sort_order', 'state']},
        ),
        migrations.AlterUniqueTogether(
            name='skillsreformdata',
            unique_together=set([('assessment_sort_order', 'performance_indicator_sort_order', 'state'), ('state', 'assessment', 'performance_indicator')]),
        ),
    ]
