# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-01-25 04:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('housing_rentalstress_uploader', '0002_housingrentalstressdata_multi_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='housingrentalstressdata',
            name='rse',
            field=models.DecimalField(decimal_places=1, default=1.0, max_digits=3),
            preserve_default=False,
        ),
    ]
