# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-06 04:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('widget_def', '0057_geowindow_view_override'),
        ('widget_data', '0013_auto_20150907_1354'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='statisticlistitem',
            options={'ordering': ('param_value', 'statistic', 'datetime_key', '-datetime_keylevel', 'sort_order')},
        ),
        migrations.AddField(
            model_name='statisticdata',
            name='param_value',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='widget_def.ParameterValue'),
        ),
        migrations.AddField(
            model_name='statisticlistitem',
            name='param_value',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='widget_def.ParameterValue'),
        ),
        migrations.AddField(
            model_name='widgetdata',
            name='param_value',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='widget_def.ParameterValue'),
        ),
        migrations.AlterField(
            model_name='statisticdata',
            name='statistic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='widget_def.Statistic'),
        ),
        migrations.AlterField(
            model_name='widgetdata',
            name='widget',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='widget_def.WidgetDefinition'),
        ),
        migrations.AlterUniqueTogether(
            name='statisticdata',
            unique_together=set([('statistic', 'param_value')]),
        ),
        migrations.AlterUniqueTogether(
            name='statisticlistitem',
            unique_together=set([('statistic', 'param_value', 'datetime_key', 'datetime_keylevel', 'sort_order')]),
        ),
        migrations.AlterUniqueTogether(
            name='widgetdata',
            unique_together=set([('widget', 'param_value')]),
        ),
    ]
