# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-08 05:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('widget_data', '0014_auto_20160606_1422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statisticdata',
            name='param_value',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='widget_def.ParametisationValue'),
        ),
        migrations.AlterField(
            model_name='statisticlistitem',
            name='param_value',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='widget_def.ParametisationValue'),
        ),
    ]
