# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-09 03:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('widget_data', '0015_auto_20160608_1552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='widgetdata',
            name='param_value',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='widget_def.ParametisationValue'),
        ),
    ]
