# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-10 00:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('widget_def', '0057_geowindow_view_override'),
        ('widget_data', '0016_auto_20160609_1307'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='graphdata',
            options={'ordering': ('graph', 'param_value', 'cluster', 'dataset', 'horiz_numericval', 'horiz_dateval', 'horiz_timeval')},
        ),
        migrations.AddField(
            model_name='graphdata',
            name='param_value',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='widget_def.ParametisationValue'),
        ),
        migrations.AlterIndexTogether(
            name='graphdata',
            index_together=set([('graph', 'param_value'), ('graph', 'param_value', 'dataset'), ('graph', 'param_value', 'dataset', 'cluster')]),
        ),
    ]
