# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-04 05:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('widget_data', '0019_auto_20160721_1428'),
    ]

    operations = [
        migrations.AddField(
            model_name='widgetdata',
            name='text_block',
            field=models.TextField(blank=True, null=True),
        ),
    ]
