# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-31 02:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('widget_def', '0069_auto_20160831_1239'),
        ('widget_data', '0020_widgetdata_text_block'),
    ]

    operations = [
        migrations.CreateModel(
            name='DynamicGraphCluster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.SlugField(verbose_name=b'label')),
                ('label', models.CharField(max_length=80, verbose_name=b'name')),
                ('hyperlink', models.URLField(blank=True, null=True)),
                ('sort_order', models.IntegerField()),
                ('graph', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='widget_def.GraphDefinition')),
                ('param_value', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='widget_def.ParametisationValue')),
            ],
            options={
                'ordering': ['graph', 'param_value', 'sort_order'],
                'abstract': False,
            },
        ),
        migrations.AlterUniqueTogether(
            name='graphclusterdata',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='graphclusterdata',
            name='cluster',
        ),
        migrations.RemoveField(
            model_name='graphclusterdata',
            name='param_value',
        ),
        migrations.DeleteModel(
            name='GraphClusterData',
        ),
        migrations.AddField(
            model_name='graphdata',
            name='dynamic_cluster',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='widget_data.DynamicGraphCluster'),
        ),
        migrations.AlterUniqueTogether(
            name='dynamicgraphcluster',
            unique_together=set([('graph', 'param_value', 'url'), ('graph', 'param_value', 'label'), ('graph', 'param_value', 'sort_order')]),
        ),
    ]
