# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-13 01:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('widget_def', '0072_auto_20160913_1113'),
        ('widget_data', '0021_auto_20160831_1239'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rawdatarecord',
            options={'ordering': ('rds', 'param_value', 'sort_order')},
        ),
        migrations.AddField(
            model_name='rawdatarecord',
            name='param_value',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='widget_def.ParametisationValue'),
        ),
        migrations.AlterUniqueTogether(
            name='rawdatarecord',
            unique_together=set([('rds', 'param_value', 'sort_order')]),
        ),
    ]
