# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-29 04:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('widget_data', '0022_auto_20160913_1113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dynamicgraphcluster',
            name='graph',
            field=models.ForeignKey(help_text=b'The graph the cluster belongs to', on_delete=django.db.models.deletion.CASCADE, to='widget_def.GraphDefinition'),
        ),
        migrations.AlterField(
            model_name='dynamicgraphcluster',
            name='hyperlink',
            field=models.URLField(blank=True, help_text=b'An optional external URL to link for this cluster ', null=True),
        ),
        migrations.AlterField(
            model_name='dynamicgraphcluster',
            name='label',
            field=models.CharField(help_text=b'A longer descriptive name for the cluster, suitable for presentation to an end user.', max_length=80, verbose_name=b'name'),
        ),
        migrations.AlterField(
            model_name='dynamicgraphcluster',
            name='sort_order',
            field=models.IntegerField(help_text=b'How to sort the cluster within the graph'),
        ),
        migrations.AlterField(
            model_name='dynamicgraphcluster',
            name='url',
            field=models.SlugField(help_text=b'A short symbolic label for the cluster, as used in the API', verbose_name=b'label'),
        ),
    ]
