# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-02-10 00:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('education_yr12_2015_uploader', '0002_educationyr12cert2attainmentdata_rse'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='educationyr12cert2attainmentdata',
            options={'ordering': ('year', 'state')},
        ),
    ]
