# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-05 04:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coag_uploader', '0002_auto_20160705_1337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='housinghomelessdata',
            name='rate_per_10k',
            field=models.DecimalField(decimal_places=1, max_digits=6),
        ),
    ]
