# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-07 03:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coag_uploader', '0004_auto_20160707_1307'),
    ]

    operations = [
        migrations.CreateModel(
            name='HigherQualificationsData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.SmallIntegerField(choices=[(1, 'NSW'), (2, 'Vic'), (3, 'Qld'), (4, 'WA'), (5, 'SA'), (6, 'Tas'), (7, 'ACT'), (8, 'NT'), (100, 'Australia')])),
                ('year', models.SmallIntegerField()),
                ('financial_year', models.BooleanField()),
                ('diploma', models.IntegerField()),
                ('adv_diploma', models.IntegerField()),
                ('total', models.IntegerField()),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='higherqualificationsdata',
            unique_together=set([('state', 'year')]),
        ),
    ]
