# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-07 03:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coag_uploader', '0006_auto_20160707_1331'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ImprovedVetGraduates',
            new_name='ImprovedVetGraduatesData',
        ),
    ]
