# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-09 01:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coag_uploader', '0007_auto_20160707_1333'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HousingRentalStressData',
        ),
    ]
