# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-10 00:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coag_uploader', '0008_delete_housingrentalstressdata'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HousingHomelessData',
        ),
    ]
