# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-07 00:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coag_uploader', '0011_delete_indigenousovercrowdingdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='higherqualificationsdata',
            name='multi_year',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='improvedvetgraduatesdata',
            name='multi_year',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='qualificationsdata',
            name='multi_year',
            field=models.IntegerField(default=1),
        ),
    ]
