# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-01-25 04:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coag_uploader', '0012_auto_20161107_1111'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HigherQualificationsData',
        ),
        migrations.DeleteModel(
            name='ImprovedVetGraduatesData',
        ),
        migrations.DeleteModel(
            name='QualificationsData',
        ),
    ]
