# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-31 03:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HousingHomelessnessNpaData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.SmallIntegerField(choices=[(1, 'NSW'), (2, 'Vic'), (3, 'Qld'), (4, 'WA'), (5, 'SA'), (6, 'Tas'), (7, 'ACT'), (8, 'NT'), (100, 'Australia')])),
                ('year', models.SmallIntegerField()),
                ('financial_year', models.BooleanField()),
                ('accomodation_needs_met', models.DecimalField(decimal_places=1, max_digits=4)),
                ('service_needs_met', models.DecimalField(decimal_places=1, max_digits=4)),
                ('clients_exp_violence', models.DecimalField(decimal_places=1, max_digits=4)),
                ('young_presenting_alone', models.DecimalField(decimal_places=1, max_digits=4)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterUniqueTogether(
            name='housinghomelessnessnpadata',
            unique_together=set([('state', 'year')]),
        ),
    ]
