# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-31 04:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('housing_homelessness_npa_uploader', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='housinghomelessnessnpadata',
            old_name='accomodation_needs_met',
            new_name='accommodation_needs_met',
        ),
    ]
