# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-21 00:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('housing_homelessness_npa_uploader', '0003_housinghomelessnessnpadata_multi_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='HousingHomelessnessNpaProgress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.SmallIntegerField(choices=[(1, 'NSW'), (2, 'Vic'), (3, 'Qld'), (4, 'WA'), (5, 'SA'), (6, 'Tas'), (7, 'ACT'), (8, 'NT'), (100, 'Australia')])),
                ('plan1', models.SmallIntegerField(choices=[(1, 'Completed'), (2, 'In progress'), (3, 'Not applicable'), (4, 'Not started')])),
                ('plan2', models.SmallIntegerField(choices=[(1, 'Completed'), (2, 'In progress'), (3, 'Not applicable'), (4, 'Not started')])),
                ('update', models.SmallIntegerField(choices=[(1, 'Completed'), (2, 'In progress'), (3, 'Not applicable'), (4, 'Not started')])),
                ('matched_funding', models.SmallIntegerField(choices=[(1, 'Completed'), (2, 'In progress'), (3, 'Not applicable'), (4, 'Not started')])),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='housinghomelessnessnpadata',
            name='service_needs_met',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='housinghomelessnessnpadata',
            name='young_presenting_alone',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='housinghomelessnessnpaprogress',
            unique_together=set([('state',)]),
        ),
    ]
