# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-21 22:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('housing_homelessness_npa_uploader', '0004_auto_20161121_1152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='housinghomelessnessnpadata',
            name='young_presenting_alone',
            field=models.DecimalField(decimal_places=1, default=10.0, max_digits=4),
            preserve_default=False,
        ),
    ]
