# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-02-10 00:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('housing_homelessness_npa_uploader', '0006_auto_20170131_1056'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='housinghomelessnessnpadata',
            options={'ordering': ('year', 'state')},
        ),
        migrations.AlterModelOptions(
            name='housinghomelessnessnpaprogress',
            options={'ordering': ('state',)},
        ),
    ]
