# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-07 00:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('housing_indigenous_overcrowding_uploader', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='indigenousovercrowdingdata',
            name='multi_year',
            field=models.IntegerField(default=1),
        ),
    ]
